### PR TITLE
Log demo module

### LINKED ISSUE #106: [new module] Log demo

### PR DESCRIPTION
**Pull request by samsonasik**
Fixes #106

### CODE REVIEW

**Comment by samsonasik** [comment]
I'm trying to re-set formatters of the Logger but it seems it not changed on loop formatters, and when changin on loop by addWriter, it got hang. @acelaya do you have an idea to re-set writers's formatter/filter so it can switch? hint : SplPriorityQueue...

**Comment by acelaya** [comment]
I've been taking a look at a project where I used a logger.
Have you tried by setting the `priority` as a config property at the same level of `options` and `name`? The Logger constructor seems to look there for it.
Instead of this

```php
'writers' => [
    [
        'name' => 'stream',
        'options' => [
            'stream' => 'php://output',
            'filters' => [
                'priority' => [
                    'name' => 'priority',
                    'options' => [
                        'priority' => \Zend\Log\Logger::DEBUG,
                    ],
                ],
            ],
            'formatter' => [
                'name' => 'simple',
                'options' => [
                    'format' => '%timestamp% %priorityName% (%priority%): %message%'.PHP_EOL,
                ],
            ],
        ],
    ],
],
```

Try with this

```php
'writers' => [
    [
        'name' => 'stream',
        'priority' => \Zend\Log\Logger::DEBUG,
        'options' => [
            'stream' => 'php://output',
            'formatter' => [
                'name' => 'simple',
                'options' => [
                    'format' => '%timestamp% %priorityName% (%priority%): %message%'.PHP_EOL,
                ],
            ],
        ],
    ],
],
```

**Comment by samsonasik** [comment]
Ok, I will try if that possible be change-able on form posted change priority/formatter. Thank you.

**Comment by samsonasik** [comment]
I'm thinking about not inject controller with Logger instance, but use 'log' config as controller property, and create new Logger on the fly when form submitted, so Logger instance can be created by : 
```php
$this->logConfig['writers']['priority'] = $data['logpriority'];
$logger = new Logger($this->logConfig);
```
I will do it..

**Comment by samsonasik** [comment]
it succeed, log generated : 
log-generated
I will write test for it ;)

**Comment by samsonasik** [comment]
it's done, ready for review ;)

**Comment by samsonasik** [comment]
@acelaya any review for this ? merge-able ?

**Comment by acelaya** [comment]
Sorry, I won't be able to test it until tomorrow evening, sorry. However
I'm sure it works fine ;)

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
It's ok for tomorrow ;). to reproduce it, there is updated
./data/sql/learnzf2.sql for addition module.
Thank you.

Warm Regards,

Abdul Malik Ikhsan


2015-02-23 17:23 GMT+07:00 Alejandro Celaya <notifications@github.com>:

**Comment by acelaya** [comment]
It properly works. It can be merged!

**Comment by samsonasik** [comment]
@acelaya merged. Thanks ;)

**Pull request merged**
