### PR TITLE
update zf2 version to ~2.4.0

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
and tests updated

**Comment by acelaya** [comment]
I'll take a look this afternoon (I hope not to forget it...)

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
thank you ;)

**Comment by acelaya** [comment]
It works perfectly fine ;-)

**Comment by samsonasik** [comment]
thank you for check, it has been merged ;)

**Pull request merged**
