### PR TITLE
Acl demo

### PR DESCRIPTION
**Pull request by samsonasik**
Implement #114 : Add ACL demo module

### CODE REVIEW

**Comment by samsonasik** [comment]
It ready for review. seems travis failed for bower install prism. will rebuilt later.

**Comment by samsonasik** [comment]
travis now green \m/. now uses bower from npm as bowerphp can't install prism dependency

**Comment by acelaya** [comment]
I'll test it this afternoon.

**Comment by samsonasik** [comment]
thank you ;)

Warm Regards,

Abdul Malik Ikhsan


2015-03-26 14:36 GMT+07:00 Alejandro Celaya <notifications@github.com>:

**Comment by samsonasik** [comment]
any review ?

**Comment by acelaya** [comment]
Sorry for the delay.
Looks great and it is working for me. It can be merged ;)

**Comment by samsonasik** [comment]
it's ok, it's merged. Thank you ;)

**Pull request merged**
