### PR TITLE
 add doctrine migration support 

### PR DESCRIPTION
**Pull request by samsonasik**
so, as new module added, we can generate new migration file and add sql insert into new generated file, and can migrate for pulled new module.

### CODE REVIEW

**Comment by samsonasik** [comment]
ready for review

**Comment by acelaya** [comment]
That's a great addition. I'll try to test it this evening.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
thanks ;)

**Comment by acelaya** [comment]
Sorry, I just realized that I forgot to test this yesterday :(
I have a local PUG meet-up today, so I won't be able to do it, but I'll
test it tomorrow.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
it's ok, take your time. Thank you ;)

Warm regards,

Abdul Malik Ikhsan

Pada 12 Mei 2015, pukul 12.11, Alejandro Celaya <notifications@github.com> menulis:

**Comment by Stanimirdim92** [comment]
I'm quite busy this week, but I will test it this weekend.

**Comment by Stanimirdim92** [comment]
Please, update ZF2 to version 2.4.2. :)

**Comment by samsonasik** [comment]
~2.4.0 in composer.json will update to latest maintenance release on
composer update based on http://framework.zend.com/long-term-support .

Warm Regards,

Abdul Malik Ikhsan


2015-05-13 1:06 GMT+07:00 Stanimir Dimitrov <notifications@github.com>:

**Comment by samsonasik** [comment]
merge-able ?

**Comment by acelaya** [comment]
I'm sorry, this has been a week with not to much free time.
I should be able to test this tomorrow.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
ok :+1:

**Comment by acelaya** [comment]
I'm testing this. It looks great, but I'm getting an error while running any migrations command, like `vendor/bin/doctrine-module migrations:migrate`.
It says this:

```
[InvalidArgumentException]                                    
There are no commands defined in the "migrations" namespace.
```

I think that migrations is not integrated in the DoctrineModule in version 0.8, could it be? However I think it is planned to be integrated in version 1.0.0

**Comment by acelaya** [comment]
Confirmed. Migrations has been added to version 0.9 https://github.com/doctrine/DoctrineORMModule/releases/tag/0.9.0

**Comment by acelaya** [comment]
Also trying to test this in master doesn't help too much... My bad.
Under the proper branch it works good!

**Comment by samsonasik** [comment]
that should be resolved by composer update. Should we use 0.9.* instead ?

**Comment by acelaya** [comment]
I don't know. It seems that there is some kind of support in version 0.8
too.

Maybe we can create another ticket in order to update DoctrineORMModule's
version.

--
Alejandro Celaya Alastrué
www.alejandrocelaya.com

**Comment by samsonasik** [comment]
Ok, I'm going to merge this for now. Thank you.

Warm regards,

Abdul Malik Ikhsan

Pada 17 Mei 2015, pukul 01.22, Alejandro Celaya <notifications@github.com> menulis:

**Pull request merged**
