### PR TITLE
Fixes render() issue on LearnZF2AjaxImageGallery

### PR DESCRIPTION
**Pull request by samsonasik**

### CODE REVIEW

**Comment by samsonasik** [comment]
@Stanimirdim92 this should fix the render issue

**Comment by samsonasik** [comment]
@Stanimirdim92 I uploaded the changes in http://learnzf2.sitrun-tech.com/learn-zf2-ajax-image-gallery , not sure why I can't upload and got error:
```
file.jpg the mimetype could not be detected from the file
```
it works locally, do you have any clues?

**Comment by samsonasik** [comment]
I've just merged master to develop as you merge to master only ;). @Stanimirdim92 could you take a look at http://learnzf2.sitrun-tech.com/learn-zf2-ajax-image-gallery and check what's wrong with upload ? Thanks.

**Comment by Stanimirdim92** [comment]
Currently looking at it. Seems lke the css is missing? The files are also not being uploaded at all. Could you send me your file.jpg via skype?

**Comment by samsonasik** [comment]
sent, it works locally, probably missing some php ext in server?

Warm Regards,

Abdul Malik Ikhsan


2015-09-24 1:49 GMT+07:00 Stanimir Dimitrov <notifications@github.com>:

**Pull request merged**
